### ISSUE TITLE
Issue with `dlopen`

### ISSUE THREAD

**Issue by RSully** [mustafa96m/iOS-Wireless-Scanner-API#1]
> dlopen(/System/Library/SystemConfiguration/IPConfiguration.bundle/IPConfiguration, 1): image not found

Running on iOS 8

**Comment by RSully** [comment]
Just noticed the note about `/Applications` - is it safe to assume this requires jailbreak?

Edit: I know readme says jailbreak only, but I just assumed that was a warning so people don't submit to the store

**Comment by RSully** [comment]
Looks like it works on device, but then the functions are all null.

**Comment by su0f** [comment]
The reason behind putting it in main Application Folder is just to run Application outside sandbox which blocks the reachability to these frameworks , the build will run with 0 error but it wouldn't be functional because the app is built under sandbox folder

**Comment by RSully** [comment]
Hmm, OK. When I run on device (built from Xcode, no jailbreak) the `dlopen` does not fail.. But, the functions from `dlsym` are all null. 

I'll experiment a bit more. If you can think of anything, let me know!

**Comment by su0f** [comment]
The dlsym() function shall obtain the address of a symbol defined within an object made accessible through a dlopen() call. The handle argument is the value returned from a call to dlopen() .. If handle does not refer to a valid object opened by dlopen(), or if the named symbol cannot be found within any of the objects associated with handle, dlsym() shall return NULL. which means the framework weren't loaded 

quoted from http://pubs.opengroup.org/onlinepubs/009695399/functions/dlsym.html check it out
