### ISSUE TITLE
App is crashing 

### ISSUE THREAD

**Issue by qamariit** [mustafa96m/iOS-Wireless-Scanner-API#3]
App is crashing on

-(id)init{
    
    if (self = [super init]) {
        //// This Required you to put your application under /Application/ in order to access this private library
        network = [[NSMutableDictionary alloc]init];
        networks = [[NSMutableArray alloc]init];
        
        
        
        libHandle = dlopen("/System/Library/SystemConfiguration/IPConfiguration.bundle/IPConfiguration", 0x1);
        char *error;
        if (libHandle == NULL && (error = dlerror()) != NULL)  {
            NSLog(@"%s",error);
            exit(1);
        }
        apple80211Open = dlsym(libHandle, "Apple80211Open");
        apple80211Bind = dlsym(libHandle, "Apple80211BindToInterface");
        apple80211Close = dlsym(libHandle, "Apple80211Close");
        apple80211Scan = dlsym(libHandle, "Apple80211Scan");

**// App is crashing on this line**
        apple80211Open(&airportHandle);
        apple80211Bind(airportHandle, @"en0"); //// This is the wireless interface . if you are a little bit hacky you can plugin your own wireless device and write it's own interface !
    }
    return self;
}

**Comment by su0f** [comment]
You should follow these steps in order to run successfully,

First of all it's a private library which means to access it you have to install the application outside the sandbox (out side application folder, beside main applications) using SSH or any other way that may help to which requires a jailbroken ios.

Thanks

**Comment by satyam90** [comment]
Using private API is not be a problem in my application. But can we make it run actual device without jail break?

**Comment by su0f** [comment]
@satyam90 In the meantime no.
